import type { RbacSnapshot, SystemPermission } from './types'

const TIMESTAMP = '2026-08-01T08:00:00.000Z'

function permission(
  id: string,
  parentId: string | null,
  name: string,
  code: string,
  type: SystemPermission['type'],
  routePath: string,
  sort: number,
): SystemPermission {
  return {
    id,
    parentId,
    name,
    code,
    type,
    routePath,
    sort,
    visible: true,
    enabled: true,
    builtIn: true,
    description: '',
    createdAt: TIMESTAMP,
    updatedAt: TIMESTAMP,
  }
}

export const DEFAULT_PERMISSIONS: readonly SystemPermission[] = [
  permission('permission-home', null, '首页', 'home:view', 'menu', '/', 10),
  permission('permission-application', null, '应用管理', 'application', 'directory', '', 20),
  permission('permission-area', 'permission-application', '管制区域', 'area:view', 'menu', '/area-control', 10),
  permission('permission-parking', 'permission-application', '停车场列表', 'parking:view', 'menu', '/parking-management', 20),
  permission('permission-parking-create', 'permission-parking', '新增停车场', 'parking:create', 'button', '', 10),
  permission('permission-parking-update', 'permission-parking', '编辑停车场', 'parking:update', 'button', '', 20),
  permission('permission-parking-delete', 'permission-parking', '删除停车场', 'parking:delete', 'button', '', 30),
  permission('permission-ticket-gate', 'permission-application', '检票口管理', 'ticket-gate:view', 'menu', '/ticket-gates', 30),
  permission('permission-ticket-gate-create', 'permission-ticket-gate', '新增检票口', 'ticket-gate:create', 'button', '', 10),
  permission('permission-ticket-gate-update', 'permission-ticket-gate', '编辑检票口', 'ticket-gate:update', 'button', '', 20),
  permission('permission-ticket-gate-delete', 'permission-ticket-gate', '删除检票口', 'ticket-gate:delete', 'button', '', 30),
  permission('permission-shuttle', 'permission-application', '接驳点管理', 'shuttle:view', 'menu', '/shuttle-points', 40),
  permission('permission-shuttle-create', 'permission-shuttle', '新增接驳点', 'shuttle:create', 'button', '', 10),
  permission('permission-shuttle-update', 'permission-shuttle', '编辑接驳点', 'shuttle:update', 'button', '', 20),
  permission('permission-shuttle-delete', 'permission-shuttle', '删除接驳点', 'shuttle:delete', 'button', '', 30),
  permission('permission-seat', 'permission-application', '座位管理', 'seat:view', 'menu', '/seats', 50),
  permission('permission-seat-create', 'permission-seat', '新增座位', 'seat:create', 'button', '', 10),
  permission('permission-seat-update', 'permission-seat', '编辑座位', 'seat:update', 'button', '', 20),
  permission('permission-seat-delete', 'permission-seat', '删除座位', 'seat:delete', 'button', '', 30),
  permission('permission-system', null, '系统管理', 'system', 'directory', '', 90),
  permission('permission-user', 'permission-system', '用户管理', 'system:user:view', 'menu', '/system/users', 10),
  permission('permission-user-create', 'permission-user', '新增用户', 'system:user:create', 'button', '', 10),
  permission('permission-user-update', 'permission-user', '编辑用户', 'system:user:update', 'button', '', 20),
  permission('permission-user-delete', 'permission-user', '删除用户', 'system:user:delete', 'button', '', 30),
  permission('permission-role', 'permission-system', '角色管理', 'system:role:view', 'menu', '/system/roles', 20),
  permission('permission-role-create', 'permission-role', '新增角色', 'system:role:create', 'button', '', 10),
  permission('permission-role-update', 'permission-role', '编辑角色', 'system:role:update', 'button', '', 20),
  permission('permission-role-delete', 'permission-role', '删除角色', 'system:role:delete', 'button', '', 30),
  permission('permission-permission', 'permission-system', '权限管理', 'system:permission:view', 'menu', '/system/permissions', 30),
  permission('permission-permission-create', 'permission-permission', '新增权限', 'system:permission:create', 'button', '', 10),
  permission('permission-permission-update', 'permission-permission', '编辑权限', 'system:permission:update', 'button', '', 20),
  permission('permission-permission-delete', 'permission-permission', '删除权限', 'system:permission:delete', 'button', '', 30),
] as const

export function createDefaultRbacSnapshot(): RbacSnapshot {
  const allPermissionIds = DEFAULT_PERMISSIONS.map((item) => item.id)
  return {
    permissions: DEFAULT_PERMISSIONS.map((item) => ({ ...item })),
    roles: [
      {
        id: 'role-super-admin',
        name: '超级管理员',
        code: 'SUPER_ADMIN',
        sort: 1,
        dataScope: 'all',
        permissionIds: allPermissionIds,
        enabled: true,
        builtIn: true,
        remark: '内置角色，拥有平台全部权限',
        createdAt: TIMESTAMP,
        updatedAt: TIMESTAMP,
      },
      {
        id: 'role-operator',
        name: '场馆运营人员',
        code: 'VENUE_OPERATOR',
        sort: 10,
        dataScope: 'department-and-children',
        permissionIds: [
          'permission-home',
          'permission-application',
          'permission-area',
          'permission-parking',
          'permission-parking-create',
          'permission-parking-update',
          'permission-ticket-gate',
          'permission-ticket-gate-create',
          'permission-ticket-gate-update',
          'permission-shuttle',
          'permission-shuttle-create',
          'permission-shuttle-update',
          'permission-seat',
          'permission-seat-create',
          'permission-seat-update',
        ],
        enabled: true,
        builtIn: false,
        remark: '负责场馆日常运营与停车场维护',
        createdAt: TIMESTAMP,
        updatedAt: TIMESTAMP,
      },
      {
        id: 'role-auditor',
        name: '只读审计员',
        code: 'READ_ONLY_AUDITOR',
        sort: 20,
        dataScope: 'all',
        permissionIds: [
          'permission-home',
          'permission-application',
          'permission-area',
          'permission-parking',
          'permission-ticket-gate',
          'permission-shuttle',
          'permission-seat',
          'permission-system',
          'permission-user',
          'permission-role',
          'permission-permission',
        ],
        enabled: true,
        builtIn: false,
        remark: '仅查看关键业务和系统配置',
        createdAt: TIMESTAMP,
        updatedAt: TIMESTAMP,
      },
    ],
    users: [
      {
        id: 'user-admin',
        username: 'admin',
        name: '平台管理员',
        phone: '13800000000',
        email: 'admin@zzsports.local',
        department: '信息中心',
        roleIds: ['role-super-admin'],
        enabled: true,
        builtIn: true,
        remark: '系统内置管理账号',
        createdAt: TIMESTAMP,
        updatedAt: TIMESTAMP,
      },
      {
        id: 'user-operator',
        username: 'operator',
        name: '运营专员',
        phone: '13800000001',
        email: 'operator@zzsports.local',
        department: '场馆运营部',
        roleIds: ['role-operator'],
        enabled: true,
        builtIn: false,
        remark: '',
        createdAt: TIMESTAMP,
        updatedAt: TIMESTAMP,
      },
    ],
  }
}
